[connections.snowflake]
account = "UIVESVB-FXB91771"
user = "Dipesh"
password = "Dipesh@1234567"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = TRUE